on:
  pull_request:
    types: [closed, closed, reopened]
    branches:
      - main
      - master
      - development
      - homologation
  
jobs:
  artia_comment_job:
    runs-on: ubuntu-latest
    name: Comment Activity.
    steps:
      - name: Comentando Atividade
        uses: solinftec/artia-new-comment-on-pull-request@main
        with: 
          organizationId: ${{ secrets.ARTIA_ORG_ID }}
          creatorEmail: ${{ secrets.ARTIA_EMAIL }}
          creatorPassword: ${{ secrets.ARTIA_PASSWORD }}